config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get "/bio" => 'home#bio', as: :bio
  get "/work" => 'home#work', as: :work
  get "/contact" => 'home#bio', as: :contact
  get "/awards" => 'home#awards', as: :awards
 
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/awards.html.erb
<h1>Hello, Awards!</h1>

app/views/home/bio.html.erb
<h1>Hello, Bio!</h1>

app/views/home/contact.html.erb
<h1>Hello, Contact!</h1>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>

app/views/home/work.html.erb
<h1>Hello, Work!</h1>

app/views/layouts/_header.html.erb
<div class="container">
  <div>
    <h1 class="font-weight-light">JACQUELYN SPENCE</h1>
  </div>
  <div class="navbar navbar-light">
    <%= link_to 'HOME', root_path, class: "navbar-text" %>
    <%= link_to 'BIO', bio_path, class: "navbar-text" %>
    <%= link_to 'WORK', work_path, class: "navbar-text" %>
    <%= link_to 'CONTACT', contact_path, class: "navbar-text" %>
    <%= link_to 'AWARDS', awards_path, class: "navbar-text" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jackie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>